insert into book_review (id, book_id, user_id, time, text) values (1, 1, 1, '31.12.2022', 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into book_review (id, book_id, user_id, time, text) values (2, 2, 2, '28.02.2023', 'etiam justo etiam pretium iaculis justo in hac habitasse platea');
insert into book_review (id, book_id, user_id, time, text) values (3, 3, 3, '10.09.2023', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into book_review (id, book_id, user_id, time, text) values (4, 4, 4, '28.10.2023', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat');
insert into book_review (id, book_id, user_id, time, text) values (5, 5, 5, '02.12.2022', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum');
insert into book_review (id, book_id, user_id, time, text) values (6, 6, 6, '09.12.2022', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum');
insert into book_review (id, book_id, user_id, time, text) values (7, 7, 7, '18.06.2023', 'venenatis turpis enim blandit mi in porttitor pede justo eu');
insert into book_review (id, book_id, user_id, time, text) values (8, 8, 8, '31.12.2022', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis');
insert into book_review (id, book_id, user_id, time, text) values (9, 9, 9, '24.02.2023', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into book_review (id, book_id, user_id, time, text) values (10, 10, 10, '28.01.2023', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into book_review (id, book_id, user_id, time, text) values (11, 11, 11, '10.10.2023', 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam');
insert into book_review (id, book_id, user_id, time, text) values (12, 12, 12, '20.01.2023', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque');
insert into book_review (id, book_id, user_id, time, text) values (13, 13, 13, '30.05.2023', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into book_review (id, book_id, user_id, time, text) values (14, 14, 14, '20.07.2023', 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam');
insert into book_review (id, book_id, user_id, time, text) values (15, 15, 15, '23.01.2023', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into book_review (id, book_id, user_id, time, text) values (16, 16, 16, '05.07.2023', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum');
insert into book_review (id, book_id, user_id, time, text) values (17, 17, 17, '23.03.2023', 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum');
insert into book_review (id, book_id, user_id, time, text) values (18, 18, 18, '22.01.2023', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into book_review (id, book_id, user_id, time, text) values (19, 19, 19, '24.03.2023', 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into book_review (id, book_id, user_id, time, text) values (20, 20, 20, '15.04.2023', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet');
insert into book_review (id, book_id, user_id, time, text) values (21, 21, 21, '31.12.2022', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus');
insert into book_review (id, book_id, user_id, time, text) values (22, 22, 22, '29.11.2022', 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into book_review (id, book_id, user_id, time, text) values (23, 23, 23, '03.10.2023', 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into book_review (id, book_id, user_id, time, text) values (24, 24, 24, '15.05.2023', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat');
insert into book_review (id, book_id, user_id, time, text) values (25, 25, 25, '22.10.2023', 'in eleifend quam a odio in hac habitasse platea dictumst');
insert into book_review (id, book_id, user_id, time, text) values (26, 26, 26, '31.10.2023', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede');
insert into book_review (id, book_id, user_id, time, text) values (27, 27, 27, '05.06.2023', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend');
insert into book_review (id, book_id, user_id, time, text) values (28, 28, 28, '09.03.2023', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into book_review (id, book_id, user_id, time, text) values (29, 29, 29, '09.02.2023', 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut');
insert into book_review (id, book_id, user_id, time, text) values (30, 30, 30, '20.01.2023', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into book_review (id, book_id, user_id, time, text) values (31, 31, 31, '21.10.2023', 'varius nulla facilisi cras non velit nec nisi vulputate nonummy');
insert into book_review (id, book_id, user_id, time, text) values (32, 32, 32, '24.05.2023', 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into book_review (id, book_id, user_id, time, text) values (33, 33, 33, '08.04.2023', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet');
insert into book_review (id, book_id, user_id, time, text) values (34, 34, 34, '10.02.2023', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into book_review (id, book_id, user_id, time, text) values (35, 35, 35, '22.09.2023', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien');
insert into book_review (id, book_id, user_id, time, text) values (36, 36, 36, '19.02.2023', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into book_review (id, book_id, user_id, time, text) values (37, 37, 37, '20.06.2023', 'maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into book_review (id, book_id, user_id, time, text) values (38, 38, 38, '08.07.2023', 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor');
insert into book_review (id, book_id, user_id, time, text) values (39, 39, 39, '10.03.2023', 'id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into book_review (id, book_id, user_id, time, text) values (40, 40, 40, '15.04.2023', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis');
insert into book_review (id, book_id, user_id, time, text) values (41, 41, 41, '26.08.2023', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into book_review (id, book_id, user_id, time, text) values (42, 42, 42, '06.07.2023', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into book_review (id, book_id, user_id, time, text) values (43, 43, 43, '02.08.2023', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut');
insert into book_review (id, book_id, user_id, time, text) values (44, 44, 44, '15.02.2023', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie');
insert into book_review (id, book_id, user_id, time, text) values (45, 45, 45, '24.05.2023', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into book_review (id, book_id, user_id, time, text) values (46, 46, 46, '11.06.2023', 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla');
insert into book_review (id, book_id, user_id, time, text) values (47, 47, 47, '16.09.2023', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget');
insert into book_review (id, book_id, user_id, time, text) values (48, 48, 48, '03.01.2023', 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into book_review (id, book_id, user_id, time, text) values (49, 49, 49, '10.02.2023', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu');
insert into book_review (id, book_id, user_id, time, text) values (50, 50, 50, '08.12.2022', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem');
insert into book_review (id, book_id, user_id, time, text) values (51, 51, 51, '10.02.2023', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis');
insert into book_review (id, book_id, user_id, time, text) values (52, 52, 52, '31.12.2022', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into book_review (id, book_id, user_id, time, text) values (53, 53, 53, '13.12.2022', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into book_review (id, book_id, user_id, time, text) values (54, 54, 54, '28.12.2022', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam');
insert into book_review (id, book_id, user_id, time, text) values (55, 55, 55, '01.02.2023', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into book_review (id, book_id, user_id, time, text) values (56, 56, 56, '13.04.2023', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis');
insert into book_review (id, book_id, user_id, time, text) values (57, 57, 57, '16.03.2023', 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut');
insert into book_review (id, book_id, user_id, time, text) values (58, 58, 58, '15.09.2023', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum');
insert into book_review (id, book_id, user_id, time, text) values (59, 59, 59, '20.08.2023', 'eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus');
insert into book_review (id, book_id, user_id, time, text) values (60, 60, 60, '06.08.2023', 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis');
insert into book_review (id, book_id, user_id, time, text) values (61, 61, 61, '26.06.2023', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea');
insert into book_review (id, book_id, user_id, time, text) values (62, 62, 62, '08.08.2023', 'justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into book_review (id, book_id, user_id, time, text) values (63, 63, 63, '01.08.2023', 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec');
insert into book_review (id, book_id, user_id, time, text) values (64, 64, 64, '09.10.2023', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into book_review (id, book_id, user_id, time, text) values (65, 65, 65, '29.11.2022', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis');
insert into book_review (id, book_id, user_id, time, text) values (66, 66, 66, '10.07.2023', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into book_review (id, book_id, user_id, time, text) values (67, 67, 67, '26.01.2023', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into book_review (id, book_id, user_id, time, text) values (68, 68, 68, '23.08.2023', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam');
insert into book_review (id, book_id, user_id, time, text) values (69, 69, 69, '07.04.2023', 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into book_review (id, book_id, user_id, time, text) values (70, 70, 70, '25.09.2023', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into book_review (id, book_id, user_id, time, text) values (71, 71, 71, '16.01.2023', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio');
insert into book_review (id, book_id, user_id, time, text) values (72, 72, 72, '24.06.2023', 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede');
insert into book_review (id, book_id, user_id, time, text) values (73, 73, 73, '20.11.2022', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est');
insert into book_review (id, book_id, user_id, time, text) values (74, 74, 74, '15.12.2022', 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus');
insert into book_review (id, book_id, user_id, time, text) values (75, 75, 75, '12.12.2022', 'ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into book_review (id, book_id, user_id, time, text) values (76, 76, 76, '25.09.2023', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac');
insert into book_review (id, book_id, user_id, time, text) values (77, 77, 77, '08.04.2023', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet');
insert into book_review (id, book_id, user_id, time, text) values (78, 78, 78, '22.07.2023', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into book_review (id, book_id, user_id, time, text) values (79, 79, 79, '14.02.2023', 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes');
insert into book_review (id, book_id, user_id, time, text) values (80, 80, 80, '11.10.2023', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into book_review (id, book_id, user_id, time, text) values (81, 81, 81, '14.04.2023', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into book_review (id, book_id, user_id, time, text) values (82, 82, 82, '02.03.2023', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into book_review (id, book_id, user_id, time, text) values (83, 83, 83, '26.08.2023', 'urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate');
insert into book_review (id, book_id, user_id, time, text) values (84, 84, 84, '25.12.2022', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis');
insert into book_review (id, book_id, user_id, time, text) values (85, 85, 85, '22.06.2023', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into book_review (id, book_id, user_id, time, text) values (86, 86, 86, '02.01.2023', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into book_review (id, book_id, user_id, time, text) values (87, 87, 87, '30.05.2023', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into book_review (id, book_id, user_id, time, text) values (88, 88, 88, '12.04.2023', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris');
insert into book_review (id, book_id, user_id, time, text) values (89, 89, 89, '23.03.2023', 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into book_review (id, book_id, user_id, time, text) values (90, 90, 90, '23.05.2023', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in');
insert into book_review (id, book_id, user_id, time, text) values (91, 91, 91, '25.01.2023', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet');
insert into book_review (id, book_id, user_id, time, text) values (92, 92, 92, '17.01.2023', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit');
insert into book_review (id, book_id, user_id, time, text) values (93, 93, 93, '04.05.2023', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla');
insert into book_review (id, book_id, user_id, time, text) values (94, 94, 94, '10.11.2023', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui');
insert into book_review (id, book_id, user_id, time, text) values (95, 95, 95, '07.08.2023', 'morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit');
insert into book_review (id, book_id, user_id, time, text) values (96, 96, 96, '09.02.2023', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum');
insert into book_review (id, book_id, user_id, time, text) values (97, 97, 97, '29.06.2023', 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu');
insert into book_review (id, book_id, user_id, time, text) values (98, 98, 98, '17.12.2022', 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien');
insert into book_review (id, book_id, user_id, time, text) values (99, 99, 99, '08.11.2023', 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate');
insert into book_review (id, book_id, user_id, time, text) values (100, 100, 100, '14.01.2023', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');