insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');

insert into authors (id, name) values (1, 'Fonsie Jalland');
insert into authors (id, name) values (2, 'Woodrow Guirardin');
insert into authors (id, name) values (3, 'Alysa Pollastrino');
insert into authors (id, name) values (4, 'Simona O''Drought');
insert into authors (id, name) values (5, 'Faydra Overstall');
insert into authors (id, name) values (6, 'Freddi Dimitresco');
insert into authors (id, name) values (7, 'Hugues Kleinbaum');
insert into authors (id, name) values (8, 'Alva Pharrow');
insert into authors (id, name) values (9, 'Hilliard Sybe');
insert into authors (id, name) values (10, 'Irvine Kift');
insert into authors (id, name) values (11, 'Bob Powell');
insert into authors (id, name) values (12, 'Helaina Celle');
insert into authors (id, name) values (13, 'Lee Tallyn');
insert into authors (id, name) values (14, 'Jobie Abramson');
insert into authors (id, name) values (15, 'Allister Tiddy');
insert into authors (id, name) values (16, 'Tessa Olenchenko');
insert into authors (id, name) values (17, 'Mathian Randles');
insert into authors (id, name) values (18, 'Jephthah Pirkis');
insert into authors (id, name) values (19, 'Kelsey Lampl');
insert into authors (id, name) values (20, 'Marleah Alesin');
insert into authors (id, name) values (21, 'Walton Afonso');
insert into authors (id, name) values (22, 'Corrie Simonich');
insert into authors (id, name) values (23, 'Cynthie Castellanos');
insert into authors (id, name) values (24, 'Shelton Iannazzi');
insert into authors (id, name) values (25, 'Maryl Wisker');
insert into authors (id, name) values (26, 'Falito Harbertson');
insert into authors (id, name) values (27, 'Nevile Charlon');
insert into authors (id, name) values (28, 'Mada Berling');
insert into authors (id, name) values (29, 'Neely Quartley');
insert into authors (id, name) values (30, 'Kristal Cottel');
insert into authors (id, name) values (31, 'Nina Callender');
insert into authors (id, name) values (32, 'Carmella Chatenet');
insert into authors (id, name) values (33, 'Berni Clamp');
insert into authors (id, name) values (34, 'Jordain Culshaw');
insert into authors (id, name) values (35, 'Lou Poizer');
insert into authors (id, name) values (36, 'Germaine Aldhous');
insert into authors (id, name) values (37, 'Ty Jonke');
insert into authors (id, name) values (38, 'Audi Brannon');
insert into authors (id, name) values (39, 'Tomkin Elton');
insert into authors (id, name) values (40, 'Cam Yanson');
insert into authors (id, name) values (41, 'Bunni Saleway');
insert into authors (id, name) values (42, 'Marsh Hymer');
insert into authors (id, name) values (43, 'Humfrey Costain');
insert into authors (id, name) values (44, 'Mickie Hansie');
insert into authors (id, name) values (45, 'Caesar Cradoc');
insert into authors (id, name) values (46, 'Brigida Dykas');
insert into authors (id, name) values (47, 'Dorri Palffrey');
insert into authors (id, name) values (48, 'Pandora Rossoni');
insert into authors (id, name) values (49, 'Dick d'' Eye');
insert into authors (id, name) values (50, 'Darci Beecroft');
insert into authors (id, name) values (51, 'Renelle Earland');
insert into authors (id, name) values (52, 'Garfield Trank');
insert into authors (id, name) values (53, 'Lin Huby');
insert into authors (id, name) values (54, 'Zachery Rahlof');
insert into authors (id, name) values (55, 'Ginny Leyban');
insert into authors (id, name) values (56, 'Bentley Hedman');
insert into authors (id, name) values (57, 'Dougy Bygate');
insert into authors (id, name) values (58, 'Cassius Calvard');
insert into authors (id, name) values (59, 'Price Yuryshev');
insert into authors (id, name) values (60, 'Dare Perulli');
insert into authors (id, name) values (61, 'Gerrie Verrico');
insert into authors (id, name) values (62, 'Joshua Browncey');
insert into authors (id, name) values (63, 'Beale Trayling');
insert into authors (id, name) values (64, 'Chrystel Pikesley');
insert into authors (id, name) values (65, 'Madeline Anstee');
insert into authors (id, name) values (66, 'Gabi Larose');
insert into authors (id, name) values (67, 'Goldarina Garnar');
insert into authors (id, name) values (68, 'Caldwell Haskett');
insert into authors (id, name) values (69, 'Edithe Basili');
insert into authors (id, name) values (70, 'Marta Faithfull');
insert into authors (id, name) values (71, 'Elyssa Treneer');
insert into authors (id, name) values (72, 'Hollie Haresnape');
insert into authors (id, name) values (73, 'Dorri Fullbrook');
insert into authors (id, name) values (74, 'Yettie MacDearmid');
insert into authors (id, name) values (75, 'Jose Heggs');
insert into authors (id, name) values (76, 'Jeanna Hasnney');
insert into authors (id, name) values (77, 'Stephani Knocker');
insert into authors (id, name) values (78, 'Curt Igoe');
insert into authors (id, name) values (79, 'Gil Lavallin');
insert into authors (id, name) values (80, 'Moira Playden');
insert into authors (id, name) values (81, 'Neill Dyzart');
insert into authors (id, name) values (82, 'Frederique Keppie');
insert into authors (id, name) values (83, 'Massimo Dockery');
insert into authors (id, name) values (84, 'Nanci Gowers');
insert into authors (id, name) values (85, 'Fern Croasdale');
insert into authors (id, name) values (86, 'Kordula Bolliver');
insert into authors (id, name) values (87, 'Demetre Sprulls');
insert into authors (id, name) values (88, 'Gideon Ayrton');
insert into authors (id, name) values (89, 'Beulah Saggers');
insert into authors (id, name) values (90, 'Tina Minucci');
insert into authors (id, name) values (91, 'Damien Roseaman');
insert into authors (id, name) values (92, 'Vasili Elcoate');
insert into authors (id, name) values (93, 'Patrica McBratney');
insert into authors (id, name) values (94, 'Ailina Brackenbury');
insert into authors (id, name) values (95, 'Lura Klaaasen');
insert into authors (id, name) values (96, 'Andris Rzehorz');
insert into authors (id, name) values (97, 'Theressa Small');
insert into authors (id, name) values (98, 'Myriam Antowski');
insert into authors (id, name) values (99, 'Lammond LAbbet');
insert into authors (id, name) values (100, 'Stephanus Hawk');